name: Flutter_Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Restore packages
        run: flutter pub get
        working-directory: ./skymanager_flutter/
      - name: Analyze
        run: flutter analyze
        working-directory: ./skymanager_flutter/
      - name: Run tests
        run: flutter test
        working-directory: ./skymanager_flutter/
